---
title: "Quant Unknowns"
format: html
---

```{r}
library(tidyverse)
library(lubridate)
library(readxl)
library(googlesheets4)
library(broom)

```

```{r}
library(readr)
Quant_Unknowns <- read_csv("RStudio_GitHub Merged Data (QUANT) - A+B Unknowns (3).csv", 
    col_types = cols(date = col_date(format = "%d-%m-%y")))
View(Quant_Unknowns)
```

```{r}
problems(Quant_Unknowns)
```

```{r}
library(readr)
Qual <- read_csv("RStudio_GitHub Merged Data (QUAL) - Qual (2).csv", 
    col_types = cols(date = col_date(format = "%d-%m-%y")))
View(Qual)
```

```{r}
problems(Qual)
```


```{r}
#| label: gender

# count
Quant_Unknowns |> 
  group_by(gender) |>
  count()

# bar chart
Quant_Unknowns |> ggplot(
  aes(x = gender, fill = gender)
) +
  geom_bar() +
  labs(title = "Genders of Children Accounted For", subtitle = "No Vaccine Cards")
ggsave("Gender_No_Vax_Card.png")

# pie chart
slices <- c(210, 191, 63)
labels <- c("Female", "Male", "Unknown")
percent <- round(slices/sum(slices)*100)
labels <- paste(labels, percent)
labels <- paste(labels,"%",sep="") 
pie(slices, labels = labels, col = rainbow(length(labels)), main = "Pie Chart of Genders Survyed (No Vaccine Cards)")

```

```{r}
#| label: age

# average age
Quant_Unknowns |>
  summarise(mean_age = mean(age, na.rm = TRUE))

# distribution of ages count
Quant_Unknowns |>
  group_by(age) |>
  count()

# distribution of ages bar chart
Quant_Unknowns |> ggplot(
  aes(x = age, fill = age)
) +
  geom_bar() +
  labs(title = "Ages of Children Accounted For", subtitle = "No Vaccine Cards")
  
# boxplot of ages
Quant_Unknowns |> ggplot(
  aes(x = age, y = gender)
) +
  geom_boxplot() +
  labs(title = "Ages of Children Accounted For", subtitle = "No Vaccine Cards")

```

```{r}
#| label: how_many_vax visualizations

# frequency table
Quant_Unknowns |>
  count(how_many_vax) |>
  mutate(prop = n/sum(n))

# bar chart
Quant_Unknowns <- Quant_Unknowns |>
  mutate(how_many_vax = as.factor(how_many_vax)) |>
  mutate(how_many_vax = factor(how_many_vax, levels = c("None", "Some", "All", "Unsure")))

Quant_Unknowns |> ggplot(
  aes(x = how_many_vax, fill = how_many_vax)
) +
  geom_bar() +
  labs(title = "Vaccination Status of Children without Vaccine Cards", 
       x = "How many vaccines has your child received?",
       y = "# of children", 
       fill = "Vaccination Status")
ggsave("Vaccination Status of Children without Vaccine Cards.png")

```

