---
title: "Quant-Qual-Correlational-Analysis"
format: html
---

```{r}
library(ggplot2)
library(dplyr)
library(tidymodels)
```

```{r}

library(readr)
QUAL_with_preg_score <- read_csv("arya copy of RStudio_GitHub Merged Data (QUAL) - Qual (1).csv")
QUAL_with_preg_score

```

```{r}
#| label: separate-group_no

QUAL_with_preg_score <- QUAL_with_preg_score |>
  mutate(grupo = str_extract(group_no, "[A-Z]+")) |>
  mutate(survey_number_non_decimal = as.integer(gsub("[^0-9]", "", group_no)))

joined_vax_cards <- joined_vax_cards |>
  mutate(grupo = str_extract(group, "[A-Z]+")) |>
  mutate(survey_number_decimal = as.numeric(str_extract(group, "[0-9.]+"))) |>
  mutate(survey_number_non_decimal = trunc(survey_number_decimal))


```

```{r}
#| label: join-vax-score-with-preg-score

vax_score_joins_preg_score <- left_join(joined_vax_cards, QUAL_with_preg_score, by = c("grupo", "survey_number_non_decimal"))

vax_score_joins_preg_score |>
  select(group, age_rounded, vax_score, grupo, survey_number_decimal, survey_number_non_decimal, group_no, colonia, preg_score) |>
  write.csv(file = "vax_and_preg_score.csv", row.names = FALSE)
```

```{r}
#| label: vax-score-vs-preg-score

removed_preg_score_NA <- vax_score_joins_preg_score |>
  filter(!is.na(preg_score)) 

removed_preg_score_NA |>
  ggplot(
    aes(x = preg_score, y = vax_score)
  ) +
  geom_point() +
  scale_y_continuous(limits = c(0, 1.25)) +
  geom_smooth(method = "lm", se = FALSE) +
  theme_minimal() +
  labs(title = "Child Vaccination Status vs. Respondent Vaccine Knowledge",
       subtitle = "(for children with vaccine cards)",
       x = "Respondent Question Response Score",
       y = "Child Vaccination Score",
       caption = "n = 265")
ggsave("Child Vaccination Status vs. Respondent Vaccine Knowledge.png")

```

```{r}
#| label: vax-status-vs-preg-score-model

model1 <- lm(vax_score ~ preg_score, data = removed_preg_score_NA)

summary(model1)

print("equation of line of best fit:  vax score = 0.7917 + 0.0228*response score")

#calc r
predicted_values <- predict(model1)  
observed_values <- removed_preg_score_NA$vax_score  
cor1 <- cor(predicted_values, observed_values)
print(cor1)

#calc rsquared
rsq1 <- summary(model1)$adj.r.squared
print(rsq1)

```


```{r}
#| label: vax-score-vs-preg-score-color-by-fam


removed_preg_score_NA |>
  ggplot(
    aes(x = preg_score, y = vax_score, color = group_no)
  ) +
  geom_point() +
  scale_y_continuous(limits = c(0, 1.25)) +
  theme_minimal() +
  labs(title = "Child Vaccination Status vs. Respondent Vaccine Knowledge",
       subtitle = "(for children with vaccine cards)",
       x = "Question Response Score",
       y = "Vaccination Score",
       caption = "(dots of the same color represent children of the same respondent)") +
  theme(legend.position = "none") +
  theme(plot.caption = element_text(size = 5))
#ggsave("Child Vaccination Status vs. Respondent Vaccine Knowledge (by family).png")

```


```{r}
#| label: vax-score-vs-preg-score-colonia-vs-not

removed_preg_score_NA |>
  ggplot(
    aes(x = preg_score, y = vax_score, color = colonia)
  ) +
  geom_point() +
  scale_y_continuous(limits = c(0, 1.25)) +
  geom_smooth(method = "lm", aes(group = colonia), se = FALSE) +
  theme_minimal() +
  labs(title = "Child Vaccination Status vs. Respondent Vaccine Knowledge",
       subtitle = "(for children with vaccine cards)",
       x = "Respondent Question Response Score",
       y = "Child Vaccination Score",
       color = "La Colonia",
       caption = "n = 265") 
ggsave("Child Vaccination Status vs. Respondent Vaccine Knowledge (Colonia).png")
```

```{r}
#| label: vax-score-vs-preg-score-colonia-model

#additive model
model2 <- lm(vax_score ~ preg_score + colonia, data = removed_preg_score_NA)

summary(model2)

print("equation of non-Colonia line of best fit:  vax score = 0.7720 + 0.0261*response score 
      equation of Colonia line of best fit: vax score = 0.7986 + 0.0218*response score 
      equation of LSRL of model: vax score = 0.7720 + 0.0235*response score + 0.0266*colonia")

#calc r
predicted_values <- predict(model2)  
observed_values <- removed_preg_score_NA$vax_score  
cor2 <- cor(predicted_values, observed_values)
print(cor2)

#calc rsquared
rsq2 <- summary(model2)$adj.r.squared
print(rsq2)

```


```{r}
#| label: vax-score-vs-age

vax_score_joins_preg_score |>
  ggplot(
    aes(x = age_rounded, y = vax_score)
  ) +
  geom_point() +
  scale_y_continuous(limits = c(0, 1.25)) +
  geom_smooth(method = "lm", se = FALSE) +
  theme_minimal() +
  labs(title = "Child Vaccination Status vs. Child Age",
       subtitle = "(for children with vaccine cards)",
       x = "Child Age",
       y = "Child Vaccination Score",
       caption = "n = 270")
#ggsave("Child Vaccination Status vs. Child Age.png")

vax_score_joins_preg_score |>
  ggplot(
    aes(x = age_rounded, y = vax_score)
  ) +
  geom_point() +
  scale_y_continuous(limits = c(0, 1.25)) +
  geom_smooth(method = "lm", se = FALSE) +
  theme_minimal() +
  labs(title = "Estado de Vacunación del Niño versus Edad del Niño",
       subtitle = "(niños con carnet de vacunación)",
       x = "Edad del Niño",
       y = "Estado de Vacunación del Niño",
       caption = "n = 270")
ggsave("Estado de Vacunación de Niño versus Edad de Niño.png")


```

```{r}
#| label: vax-score-vs-age-model

model3 <- lm(vax_score ~ age_rounded, data = removed_preg_score_NA)

summary(model3)

print("equation of line of best fit:  vax score = 0.9349 + -0.0051*child age")

#calc r
predicted_values <- predict(model3)  
observed_values <- removed_preg_score_NA$vax_score  
cor3 <- cor(predicted_values, observed_values)
print(cor3)

#calc rsquared
rsq3 <- summary(model3)$adj.r.squared
print(rsq3)

```


```{r}
#| label: vax-score-vs-last-grade

removed_preg_score_NA |>
  ggplot(
    aes(x = last_grade, y = vax_score)
  ) +
  geom_point() +
  scale_y_continuous(limits = c(0, 1.25)) +
  geom_smooth(method = "lm", se = FALSE) +
  theme_minimal() +
  labs(title = "Child Vaccination Status vs. Respondent's Education Level",
       subtitle = "(for children with vaccine cards)",
       x = "Respondent's Last Grade of School Completed",
       y = "Child Vaccination Score", 
       caption = "n = 257")
ggsave("Child Vaccination Status vs. Respondent's Education Level.png")

```

```{r}
#| label: vax-score-vs-education-model

removed_last_grade_NA <- removed_preg_score_NA |>
  filter(!is.na(last_grade))

model4 <- lm(vax_score ~ last_grade, data = removed_last_grade_NA)

summary(model4)

print("equation of line of best fit:  vax score = 0.9278 + -0.0016*last grade")

#calc r
predicted_values <- predict(model4)  
observed_values <- removed_last_grade_NA$vax_score  
cor4 <- cor(predicted_values, observed_values)
print(cor4)

#calc rsquared
rsq4 <- summary(model4)$adj.r.squared
print(rsq4)
```

```{r}
#| label: vax-score-dist

removed_preg_score_NA |>
  ggplot(
    aes(y = vax_score)
  ) +
  geom_boxplot(width = 0.5) +
  scale_y_continuous(limits = c(0, 1.1)) +
  theme_minimal() +
  theme(legend.position = "none") +
  labs(title = "Distribution of Child Vaccination Scores",
       subtitle = "(for all children with vaccine cards)",
       y = "Child Vaccination Score",
       caption = "n = 270") +
  theme(axis.text.x = element_blank())
ggsave("Distribution of Child Vaccination Scores.png")
  
mean_vax_score = mean(vax_score_joins_preg_score$vax_score)
print(mean_vax_score)

```


```{r}
#| label: vax-score-colonia-vs-not

removed_preg_score_NA |>
  ggplot(
    aes(x = colonia, y = vax_score, color = colonia)
  ) +
  geom_boxplot() +
  scale_y_continuous(limits = c(0, 1.1)) +
  theme_minimal() +
  theme(legend.position = "none") +
  labs(title = "Distribution of Child Vaccination Scores in La Colonia vs. Non-Colonia",
       subtitle = "(for children with vaccine cards)",
       x = "La Colonia",
       y = "Child Vaccination Score",
       caption = "n = 270") 
ggsave("Distribution of Child Vaccination Scores in La Colonia vs. Non-Colonia.png")

vax_score_joins_preg_score_colonia <- vax_score_joins_preg_score |>
  filter(colonia == "Yes") 
  
mean_vax_score_colonia = mean(vax_score_joins_preg_score_colonia$vax_score)
print(mean_vax_score_colonia)

vax_score_joins_preg_score_non_colonia <- vax_score_joins_preg_score |>
  filter(colonia == "No") 
  
mean_vax_score_non_colonia = mean(vax_score_joins_preg_score_non_colonia$vax_score)
print(mean_vax_score_non_colonia)

# t-test
set.seed(123)
colonia_group <- rnorm(161, mean = mean_vax_score_colonia, sd = 2)
non_colonia_group <- rnorm(109, mean = mean_vax_score_non_colonia, sd = 2)

t_test <- t.test(colonia_group, non_colonia_group)

print(t_test)
```

```{r}
#| label: t-test-question-response-score-colonia

Qual_island_region |>
  count(colonia)

set.seed(123)
colonia_group <- rnorm(187, mean = 5.3, sd = 2)
non_colonia_group <- rnorm(249, mean = 5.25, sd = 2)

t_test <- t.test(colonia_group, non_colonia_group)

print(t_test)
```


```{r}
library(readr)
Qual_island_region <- read_csv("RStudio_GitHub Merged Data (QUAL) - Qual (3).csv", 
    col_types = cols(date = col_date(format = "%d-%m-%y")))
View(RStudio_GitHub_Merged_Data_QUAL_Qual_3_)
```

```{r}
#| label: vax-score-joins-preg-score-joins-island-region

joined_vax_cards <- joined_vax_cards |>
  mutate(group_no = paste0(grupo, survey_number_non_decimal))

vax_score_joins_island_region <- left_join(vax_score_joins_preg_score, Qual_island_region, by = "group_no")

vax_score_joins_island_region_selected <- vax_score_joins_island_region |>
  select(group, vax_score, group_no, island_region, preg_score) 

```

```{r}
#| label: vax-score-vs-preg-score-by-island-region

no_preg_NA <- vax_score_joins_island_region_selected |>
  filter(!is.na(preg_score))

no_preg_NA |>
  ggplot(
    aes(x = preg_score, y = vax_score, color = island_region)
  ) +
  geom_point() +
  scale_y_continuous(limits = c(0, 1.25)) +
  geom_smooth(method = "lm", aes(group = island_region), se = FALSE) +
  theme_minimal() +
  labs(title = "Child Vaccination Status vs. Respondent Vaccine Knowledge",
       subtitle = "(for children with vaccine cards)",
       x = "Respondent Question Response Score",
       y = "Child Vaccination Score",
       color = "Island Region",
       caption = "n = 265") 
ggsave("Child Vaccination Status vs. Respondent Vaccine Knowledge by Island Region.png")

```

```{r}

#additive model
model5 <- lm(vax_score ~ preg_score + island_region, data = no_preg_NA)

summary(model5)

print("equation of LSRL of model: vax score = 0.7900 + 0.0223*response score + 0.0034*island region")

#calc r
predicted_values <- predict(model5)  
observed_values <- no_preg_NA$vax_score  
cor5 <- cor(predicted_values, observed_values)
print(cor5)

#calc rsquared
rsq5 <- summary(model5)$adj.r.squared
print(rsq5)
```

```{r}
#| label: vax-score-dist-by-island-region

vax_score_joins_island_region_selected |>
  ggplot(
    aes(x = as.factor(island_region), y = vax_score, color = island_region)
  ) +
  geom_boxplot() +
  scale_y_continuous(limits = c(0, 1.1)) +
  theme_minimal() +
  theme(legend.position = "none") +
  labs(title = "Distribution of Child Vaccination Scores in the 5 Island Regions",
       subtitle = "(for children with vaccine cards)",
       x = "Island Region",
       y = "Child Vaccination Score",
       caption = "n = 270") 
ggsave("Distribution of Child Vaccination Scores in 5 Island Regions.png")

region1 <- vax_score_joins_island_region_selected |>
  filter(island_region == "1") 
mean1 = mean(region1$vax_score)
print(mean1)

region2 <- vax_score_joins_island_region_selected |>
  filter(island_region == "2") 
mean2 = mean(region2$vax_score)
print(mean2)

region3 <- vax_score_joins_island_region_selected |>
  filter(island_region == "3") 
mean3 = mean(region3$vax_score)
print(mean3)

region4 <- vax_score_joins_island_region_selected |>
  filter(island_region == "4") 
mean4 = mean(region4$vax_score)
print(mean4)

region5 <- vax_score_joins_island_region_selected |>
  filter(island_region == "5") 
mean5 = mean(region5$vax_score)
print(mean5)

```


```{r}
#| label: preg-score-dist-island-region

all_surveys_no_preg_score_NA <- arya_copy_of_RStudio_GitHub_Merged_Data_QUAL_Qual_1_ |>
  filter(!is.na(preg_score))

preg_score_joins_island_region <- left_join(all_surveys_no_preg_score_NA, Qual_island_region, by = "group_no")

preg_score_joins_island_region_selected <- preg_score_joins_island_region |>
  select(group_no, island_region, preg_score) 

preg_score_joins_island_region |>
  ggplot(
    aes(x = as.factor(island_region), y = preg_score, color = island_region)
  ) +
  geom_boxplot() +
  scale_y_continuous(limits = c(0, 6)) +
  theme_minimal() +
  theme(legend.position = "none") +
  labs(title = "Vaccine Knowledge Question Response Scores in 5 Island Regions",
       x = "Island Region",
       y = "Question Response Score",
       caption = "n = 429") 
ggsave("Distribution of Vax Knowledge Question Scores in 5 Island Regions.png")

r1 <- preg_score_joins_island_region |>
  filter(island_region == "1") 
m1 = mean(r1$preg_score)
print(m1)

r2 <- preg_score_joins_island_region |>
  filter(island_region == "2") 
m2 = mean(r2$preg_score)
print(m2)

r3 <- preg_score_joins_island_region |>
  filter(island_region == "3") 
m3 = mean(r3$preg_score)
print(m3)

r4 <- preg_score_joins_island_region |>
  filter(island_region == "4") 
m4 = mean(r4$preg_score)
print(m4)

r5 <- preg_score_joins_island_region |>
  filter(island_region == "5") 
m5 = mean(r5$preg_score)
print(m5)
```

```{r}
#| label: preg-score-dist-colonia

preg_score_joins_island_region |>
  ggplot(
    aes(x = colonia.x, y = preg_score, color = colonia.x)
  ) +
  geom_boxplot() +
  scale_y_continuous(limits = c(0, 6)) +
  theme_minimal() +
  theme(legend.position = "none") +
  labs(title = "Vaccine Knowledge Question Response Scores in La Colonia vs. Not",
       x = "La Colonia",
       y = "Question Response Score",
       caption = "n = 429") 
ggsave("Distribution of Vax Knowledge Question Scores in La Colonia vs Not.png")

r1c <- preg_score_joins_island_region |>
  filter(colonia.x == "Yes") 
m1c = mean(r1c$preg_score)
print(m1c)

r2nc <- preg_score_joins_island_region |>
  filter(colonia.x == "No") 
m2nc = mean(r2nc$preg_score)
print(m2nc)

```

