---
title: "Quant Vax Cards"
format: html
---

```{r}
library(tidyverse)
library(lubridate)
library(readxl)
library(googlesheets4)
library(broom)
```

```{r}

library(readr)
Consolidated_QUANT_Vax_Cards <- read_csv("Consolidated QUANT Vax Cards POLIO SHIFTED - FINAL (shifted polios, deleted cols, etc) (3).csv", 
    col_types = cols(date = col_date(format = "%d-%m-%y"), 
        dob = col_date(format = "%d-%m-%Y")))
#View(Consolidated_QUANT_Vax_Cards_POLIO_SHIFTED_FINAL_shifted_polios_deleted_cols_etc_3_)

```

```{r}
Consolidated_QUANT_Vax_Cards |>
  count(colonia_status)
```

```{r}
#| label: gender

# frequency table
Consolidated_QUANT_Vax_Cards |>
  count(gender) |>
  mutate(prop = n/sum(n))

# bar chart
Consolidated_QUANT_Vax_Cards |> ggplot(
  aes(x = gender, fill = gender)
) +
  geom_bar() +
  labs(title = "Genders of Children Accounted For", subtitle = "with Vaccine Cards")

# pie chart
slices <- c(122, 132, 16)
labels <- c("Female", "Male", "Unknown")
percent <- round(slices/sum(slices)*100)
labels <- paste(labels, percent)
labels <- paste(labels,"%",sep="") 
pie(slices, labels = labels, col = rainbow(length(labels)), main = "Pie Chart of Genders Survyed (with Vaccine Cards)")
  
```

```{r}
#| label: desired-vax-score

vax_score_tibble <- Consolidated_QUANT_Vax_Cards |>
  select(group, date, gender, dob, colonia_status) 

vax_score_tibble <- vax_score_tibble |>
  mutate(age_in_days = date - dob) |>
  mutate(age_in_years = as.numeric(age_in_days) / 365.25) |>
  mutate(age_rounded = round(age_in_years, 1))


vax_score_tibble <- vax_score_tibble |>
  mutate(desired_vax_score = if_else(age_rounded < 0.2, 2, 
                              if_else(age_rounded >= 0.2 & age_rounded < 0.3, 6,
                               if_else(age_rounded >= 0.3 & age_rounded < 0.5, 10,
                                if_else(age_rounded >= 0.5 & age_rounded < 1.0, 13, 
                                 if_else(age_rounded >= 1.0 & age_rounded < 1.5, 15,
                                  if_else(age_rounded >= 1.5 & age_rounded < 4, 18,
                                   if_else(age_rounded >= 4 & age_rounded < 11, 19,
                                    if_else(age_rounded >= 11 & gender == "M", 20,
                                     if_else(age_rounded >= 11 & gender == "F", 21, 0))))))))))

vax_score_tibble <- vax_score_tibble |>
  select(group, dob, age_rounded, desired_vax_score, colonia_status) 
vax_score_tibble

```

```{r}
#| label: actual-vax-score

vaccine_schedule <- Consolidated_QUANT_Vax_Cards 

vaccine_final <- data.frame(
  colonia_status = vaccine_schedule$colonia_status,
  survey_date = vaccine_schedule$date,
  group = vaccine_schedule$group,
  child_gender = vaccine_schedule$gender,
  child_dob = vaccine_schedule$dob,
  hep_b_status = ifelse(!is.na(vaccine_schedule$hep_b), "YES", "NO"),
  bcg_status = ifelse(!is.na(vaccine_schedule$bcg), "YES", "NO"),
  polio_vpi1_status = ifelse(!is.na(vaccine_schedule$polio_vpi1), "YES", "NO"),
  polio_vpi2_status = ifelse(!is.na(vaccine_schedule$polio_vpi2), "YES", "NO"),
  polio_vop1_status = ifelse(!is.na(vaccine_schedule$polio_vop1), "YES", "NO"),
  polio_vop2_status = ifelse(!is.na(vaccine_schedule$polio_vop2), "YES", "NO"),
  penta1_status = ifelse(!is.na(vaccine_schedule$penta1), "YES", "NO"),
  penta2_status = ifelse(!is.na(vaccine_schedule$penta2), "YES", "NO"),
  penta3_status = ifelse(!is.na(vaccine_schedule$penta3), "YES", "NO"),
  neumo1_status = ifelse(!is.na(vaccine_schedule$neumo1), "YES", "NO"),
  neumo2_status = ifelse(!is.na(vaccine_schedule$neumo2), "YES", "NO"),
  neumo3_status = ifelse(!is.na(vaccine_schedule$neumo3), "YES", "NO"),
  rota1_status = ifelse(!is.na(vaccine_schedule$rota1), "YES", "NO"),
  rota2_status = ifelse(!is.na(vaccine_schedule$rota2), "YES", "NO"),
  srp1_status = ifelse(!is.na(vaccine_schedule$srp1), "YES", "NO"),
  srp2_status = ifelse(!is.na(vaccine_schedule$srp2), "YES", "NO"),
  hep_a_status = ifelse(!is.na(vaccine_schedule$hep_a), "YES", "NO"),
  dpt1_status = ifelse(!is.na(vaccine_schedule$dpt1), "YES", "NO"),
  dpt2_status = ifelse(!is.na(vaccine_schedule$dpt2), "YES", "NO"),
  vph_1_status = ifelse(!is.na(vaccine_schedule$vph_1), "YES", "NO"),
  tetanus_dip_status = ifelse(!is.na(vaccine_schedule$tetanus_dip), "YES", "NO"))

vaccine_final <- vaccine_final |>
  rowwise() |>
  mutate(yes_count = sum(c_across(hep_b_status:tetanus_dip_status) == "YES"))
print(vaccine_final)

vaccine_final <- vaccine_final |>
  rename(dob = child_dob)

actual_vax_score <- vaccine_final |>
  as_tibble() |>
  select(group, dob, yes_count, colonia_status)

```

```{r}
#| label: join!

joined_vax_cards <- actual_vax_score |>
  left_join(vax_score_tibble, by = join_by(group))

```

```{r}
#| label: has-all-vax

joined_vax_cards <- joined_vax_cards |>
  mutate(complete = if_else(yes_count >= desired_vax_score, TRUE, FALSE))
joined_vax_cards

joined_vax_cards |>
  count(complete)
```

```{r}
#| label: should-and-match-cols

new_tibble <- vax_score_tibble |>
  left_join(vaccine_final, by = join_by(group)) |>
  select(!c(group, dob.x, dob.y, survey_date)) 

new_tibble <- new_tibble |>
  mutate(hep_b_should = if_else(age_rounded > 0, "YES", "NO")) |>
  mutate(hep_b_match = if_else(hep_b_status == hep_b_should & hep_b_status == "YES", "YES", "NO")) |>
  mutate(bcg_should = if_else(age_rounded > 0, "YES", "NO")) |>
  mutate(bcg_match = if_else(bcg_status == bcg_should & bcg_status == "YES", "YES", "NO")) |>
  mutate(polio_vpi1_should = if_else(age_rounded >= 0.2, "YES", "NO")) |>
  mutate(polio_vpi1_match = if_else(polio_vpi1_status == polio_vpi1_should & polio_vpi1_status == "YES", "YES", "NO")) |>
  mutate(polio_vpi2_should = if_else(age_rounded >= 0.3, "YES", "NO")) |>
  mutate(polio_vpi2_match = if_else(polio_vpi2_status == polio_vpi2_should & polio_vpi2_status == "YES", "YES", "NO")) |>
  mutate(polio_vop1_should = if_else(age_rounded >= 0.5, "YES", "NO")) |>
  mutate(polio_vop1_match = if_else(polio_vop1_status == polio_vop1_should & polio_vop1_status == "YES", "YES", "NO")) |>
  mutate(polio_vop2_should = if_else(age_rounded >= 1.5, "YES", "NO")) |>
  mutate(polio_vop2_match = if_else(polio_vop2_status == polio_vop2_should & polio_vop2_status == "YES", "YES", "NO")) |>
  mutate(penta1_should = if_else(age_rounded >= 0.2, "YES", "NO")) |>
  mutate(penta1_match = if_else(penta1_status == penta1_should & penta1_status == "YES", "YES", "NO")) |>
  mutate(penta2_should = if_else(age_rounded >= 0.3, "YES", "NO")) |>
  mutate(penta2_match = if_else(penta2_status == penta2_should & penta2_status == "YES", "YES", "NO")) |>
  mutate(penta3_should = if_else(age_rounded >= 0.5, "YES", "NO")) |>
  mutate(penta3_match = if_else(penta3_status == penta3_should & penta3_status == "YES", "YES", "NO")) |>
  mutate(neumo1_should = if_else(age_rounded >= 0.2, "YES", "NO")) |>
  mutate(neumo1_match = if_else(neumo1_status == neumo1_should & neumo1_status == "YES", "YES", "NO")) |>
  mutate(neumo2_should = if_else(age_rounded >= 0.3, "YES", "NO")) |>
  mutate(neumo2_match = if_else(neumo2_status == neumo2_should & neumo2_status == "YES", "YES", "NO")) |>
  mutate(neumo3_should = if_else(age_rounded >= 0.5, "YES", "NO")) |>
  mutate(neumo3_match = if_else(neumo3_status == neumo3_should & neumo3_status == "YES", "YES", "NO")) |>
  mutate(rota1_should = if_else(age_rounded >= 0.2, "YES", "NO")) |>
  mutate(rota1_match = if_else(rota1_status == rota1_should & rota1_status == "YES", "YES", "NO")) |>
  mutate(rota2_should = if_else(age_rounded >= 0.3, "YES", "NO")) |>
  mutate(rota2_match = if_else(rota2_status == rota2_should & rota2_status == "YES", "YES", "NO")) |>
  mutate(srp1_should = if_else(age_rounded >= 1.0, "YES", "NO")) |>
  mutate(srp1_match = if_else(srp1_status == srp1_should & srp1_status == "YES", "YES", "NO")) |>
  mutate(srp2_should = if_else(age_rounded >= 1.5, "YES", "NO")) |>
  mutate(srp2_match = if_else(srp2_status == srp2_should & srp2_status == "YES", "YES", "NO")) |>
  mutate(hep_a_should = if_else(age_rounded >= 1.0, "YES", "NO")) |>
  mutate(hep_a_match = if_else(hep_a_status == hep_a_should & hep_a_status == "YES", "YES", "NO")) |>
  mutate(dpt1_should = if_else(age_rounded >= 1.5, "YES", "NO")) |>
  mutate(dpt1_match = if_else(dpt1_status == dpt1_should & dpt1_status == "YES", "YES", "NO")) |>
  mutate(dpt2_should = if_else(age_rounded >= 4, "YES", "NO")) |>
  mutate(dpt2_match = if_else(dpt2_status == dpt2_should & dpt2_status == "YES", "YES", "NO")) |>
  mutate(vph_1_should = if_else(age_rounded >= 11  & child_gender == "F", "YES", "NO")) |>
  mutate(vph_1_match = if_else(vph_1_status == vph_1_should & vph_1_status == "YES", "YES", "NO")) |>
  mutate(tetanus_dip_should = if_else(age_rounded >= 11, "YES", "NO")) |>
  mutate(tetanus_dip_match = if_else(tetanus_dip_status == tetanus_dip_should & tetanus_dip_status == "YES", "YES", "NO"))

```

```{r}
#| label: each-vax-adherence-calcs-for-all-cards

###### Hep B ######
match_tibble <- new_tibble |>
  count(hep_b_match)

num_yes_match <- match_tibble |>
  filter(hep_b_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- new_tibble |>
  count(hep_b_should)

num_yes_should <- should_tibble |>
  filter(hep_b_should == "YES") |>
  pull(n)
print(num_yes_should)

hep_b_percent_adherence = num_yes_match / num_yes_should
print(hep_b_percent_adherence)

######  BCG  #########

match_tibble <- new_tibble |>
  count(bcg_match)

num_yes_match <- match_tibble |>
  filter(bcg_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- new_tibble |>
  count(bcg_should)

num_yes_should <- should_tibble |>
  filter(bcg_should == "YES") |>
  pull(n)
print(num_yes_should)

bcg_percent_adherence = num_yes_match / num_yes_should
print(bcg_percent_adherence)

###### Polio VPI 1 #########

match_tibble <- new_tibble |>
  count(polio_vpi1_match)

num_yes_match <- match_tibble |>
  filter(polio_vpi1_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- new_tibble |>
  count(polio_vpi1_should)

num_yes_should <- should_tibble |>
  filter(polio_vpi1_should == "YES") |>
  pull(n)
print(num_yes_should)

polio_vpi1_percent_adherence = num_yes_match / num_yes_should
print(polio_vpi1_percent_adherence)

###### Polio VPI 2 #########

match_tibble <- new_tibble |>
  count(polio_vpi2_match)

num_yes_match <- match_tibble |>
  filter(polio_vpi2_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- new_tibble |>
  count(polio_vpi2_should)

num_yes_should <- should_tibble |>
  filter(polio_vpi2_should == "YES") |>
  pull(n)
print(num_yes_should)

polio_vpi2_percent_adherence = num_yes_match / num_yes_should
print(polio_vpi2_percent_adherence)

###### Polio VOP 1 #########

match_tibble <- new_tibble |>
  count(polio_vop1_match)

num_yes_match <- match_tibble |>
  filter(polio_vop1_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- new_tibble |>
  count(polio_vop1_should)

num_yes_should <- should_tibble |>
  filter(polio_vop1_should == "YES") |>
  pull(n)
print(num_yes_should)

polio_vop1_percent_adherence = num_yes_match / num_yes_should
print(polio_vop1_percent_adherence)

###### Polio VOP 2 #########

match_tibble <- new_tibble |>
  count(polio_vop2_match)

num_yes_match <- match_tibble |>
  filter(polio_vop2_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- new_tibble |>
  count(polio_vop2_should)

num_yes_should <- should_tibble |>
  filter(polio_vop2_should == "YES") |>
  pull(n)
print(num_yes_should)

polio_vop2_percent_adherence = num_yes_match / num_yes_should
print(polio_vop2_percent_adherence)

###### Penta 1 #########

match_tibble <- new_tibble |>
  count(penta1_match)

num_yes_match <- match_tibble |>
  filter(penta1_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- new_tibble |>
  count(penta1_should)

num_yes_should <- should_tibble |>
  filter(penta1_should == "YES") |>
  pull(n)
print(num_yes_should)

penta1_percent_adherence = num_yes_match / num_yes_should
print(penta1_percent_adherence)

###### Penta 2 #########

match_tibble <- new_tibble |>
  count(penta2_match)

num_yes_match <- match_tibble |>
  filter(penta2_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- new_tibble |>
  count(penta2_should)

num_yes_should <- should_tibble |>
  filter(penta2_should == "YES") |>
  pull(n)
print(num_yes_should)

penta2_percent_adherence = num_yes_match / num_yes_should
print(penta2_percent_adherence)

###### Penta 3 #########

match_tibble <- new_tibble |>
  count(penta3_match)

num_yes_match <- match_tibble |>
  filter(penta3_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- new_tibble |>
  count(penta3_should)

num_yes_should <- should_tibble |>
  filter(penta3_should == "YES") |>
  pull(n)
print(num_yes_should)

penta3_percent_adherence = num_yes_match / num_yes_should
print(penta3_percent_adherence) ##we should double check this one because why is it at 100%-

###### Neumo 1 #########

match_tibble <- new_tibble |>
  count(neumo1_match)

num_yes_match <- match_tibble |>
  filter(neumo1_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- new_tibble |>
  count(neumo1_should)

num_yes_should <- should_tibble |>
  filter(neumo1_should == "YES") |>
  pull(n)
print(num_yes_should)

neumo1_percent_adherence = num_yes_match / num_yes_should
print(neumo1_percent_adherence)

###### Neumo 2 #########

match_tibble <- new_tibble |>
  count(neumo2_match)

num_yes_match <- match_tibble |>
  filter(neumo2_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- new_tibble |>
  count(neumo2_should)

num_yes_should <- should_tibble |>
  filter(neumo2_should == "YES") |>
  pull(n)
print(num_yes_should)

neumo2_percent_adherence = num_yes_match / num_yes_should
print(neumo2_percent_adherence)

###### Neumo 3 #########

match_tibble <- new_tibble |>
  count(neumo3_match)

num_yes_match <- match_tibble |>
  filter(neumo3_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- new_tibble |>
  count(neumo3_should)

num_yes_should <- should_tibble |>
  filter(neumo3_should == "YES") |>
  pull(n)
print(num_yes_should)

neumo3_percent_adherence = num_yes_match / num_yes_should
print(neumo3_percent_adherence)

###### Rota 1 #########

match_tibble <- new_tibble |>
  count(rota1_match)

num_yes_match <- match_tibble |>
  filter(rota1_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- new_tibble |>
  count(rota1_should)

num_yes_should <- should_tibble |>
  filter(rota1_should == "YES") |>
  pull(n)
print(num_yes_should)

rota1_percent_adherence = num_yes_match / num_yes_should
print(rota1_percent_adherence)

###### Rota 2 #########

match_tibble <- new_tibble |>
  count(rota2_match)

num_yes_match <- match_tibble |>
  filter(rota2_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- new_tibble |>
  count(rota2_should)

num_yes_should <- should_tibble |>
  filter(rota2_should == "YES") |>
  pull(n)
print(num_yes_should)

rota2_percent_adherence = num_yes_match / num_yes_should
print(rota2_percent_adherence)

###### SRP 1 #########

match_tibble <- new_tibble |>
  count(srp1_match)

num_yes_match <- match_tibble |>
  filter(srp1_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- new_tibble |>
  count(srp1_should)

num_yes_should <- should_tibble |>
  filter(srp1_should == "YES") |>
  pull(n)
print(num_yes_should)

srp1_percent_adherence = num_yes_match / num_yes_should
print(srp1_percent_adherence)

###### SRP 2 #########

match_tibble <- new_tibble |>
  count(srp2_match)

num_yes_match <- match_tibble |>
  filter(srp2_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- new_tibble |>
  count(srp2_should)

num_yes_should <- should_tibble |>
  filter(srp2_should == "YES") |>
  pull(n)
print(num_yes_should)

srp2_percent_adherence = num_yes_match / num_yes_should
print(srp2_percent_adherence)

###### Hep A #########

match_tibble <- new_tibble |>
  count(hep_a_match)

num_yes_match <- match_tibble |>
  filter(hep_a_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- new_tibble |>
  count(hep_a_should)

num_yes_should <- should_tibble |>
  filter(hep_a_should == "YES") |>
  pull(n)
print(num_yes_should)

hep_a_percent_adherence = num_yes_match / num_yes_should
print(hep_a_percent_adherence)

###### DPT 1 #########

match_tibble <- new_tibble |>
  count(dpt1_match)

num_yes_match <- match_tibble |>
  filter(dpt1_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- new_tibble |>
  count(dpt1_should)

num_yes_should <- should_tibble |>
  filter(dpt1_should == "YES") |>
  pull(n)
print(num_yes_should)

dpt1_percent_adherence = num_yes_match / num_yes_should
print(dpt1_percent_adherence)

###### DPT 2 #########

match_tibble <- new_tibble |>
  count(dpt2_match)

num_yes_match <- match_tibble |>
  filter(dpt2_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- new_tibble |>
  count(dpt2_should)

num_yes_should <- should_tibble |>
  filter(dpt2_should == "YES") |>
  pull(n)
print(num_yes_should)

dpt2_percent_adherence = num_yes_match / num_yes_should
print(dpt2_percent_adherence)

###### VPH 1 #########

match_tibble <- new_tibble |>
  count(vph_1_match)

num_yes_match <- match_tibble |>
  filter(vph_1_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- new_tibble |>
  count(vph_1_should)

num_yes_should <- should_tibble |>
  filter(vph_1_should == "YES") |>
  pull(n)
print(num_yes_should)

vph_1_percent_adherence = num_yes_match / num_yes_should
print(vph_1_percent_adherence)

###### Tetanus Diptheria #########

match_tibble <- new_tibble |>
  count(tetanus_dip_match)

num_yes_match <- match_tibble |>
  filter(tetanus_dip_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- new_tibble |>
  count(tetanus_dip_should)

num_yes_should <- should_tibble |>
  filter(tetanus_dip_should == "YES") |>
  pull(n)
print(num_yes_should)

tetanus_dip_percent_adherence = num_yes_match / num_yes_should
print(tetanus_dip_percent_adherence)

# take YES match vax1 / YES should vax1
```

```{r}
#| label: each-vax-adherence-calcs-for-colonia-only

colonia_tibble <- new_tibble |>
  filter(colonia_status.x == "Yes")

###### Hep B ######
match_tibble <- colonia_tibble |>
  count(hep_b_match)

num_yes_match <- match_tibble |>
  filter(hep_b_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- colonia_tibble |>
  count(hep_b_should)

num_yes_should <- should_tibble |>
  filter(hep_b_should == "YES") |>
  pull(n)
print(num_yes_should)

hep_b_percent_adherence = num_yes_match / num_yes_should
print(hep_b_percent_adherence)

######  BCG  #########

match_tibble <- colonia_tibble |>
  count(bcg_match)

num_yes_match <- match_tibble |>
  filter(bcg_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- colonia_tibble |>
  count(bcg_should)

num_yes_should <- should_tibble |>
  filter(bcg_should == "YES") |>
  pull(n)
print(num_yes_should)

bcg_percent_adherence = num_yes_match / num_yes_should
print(bcg_percent_adherence)

###### Polio VPI 1 #########

match_tibble <- colonia_tibble |>
  count(polio_vpi1_match)

num_yes_match <- match_tibble |>
  filter(polio_vpi1_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- colonia_tibble |>
  count(polio_vpi1_should)

num_yes_should <- should_tibble |>
  filter(polio_vpi1_should == "YES") |>
  pull(n)
print(num_yes_should)

polio_vpi1_percent_adherence = num_yes_match / num_yes_should
print(polio_vpi1_percent_adherence)

###### Polio VPI 2 #########

match_tibble <- colonia_tibble |>
  count(polio_vpi2_match)

num_yes_match <- match_tibble |>
  filter(polio_vpi2_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- colonia_tibble |>
  count(polio_vpi2_should)

num_yes_should <- should_tibble |>
  filter(polio_vpi2_should == "YES") |>
  pull(n)
print(num_yes_should)

polio_vpi2_percent_adherence = num_yes_match / num_yes_should
print(polio_vpi2_percent_adherence)

###### Polio VOP 1 #########

match_tibble <- colonia_tibble |>
  count(polio_vop1_match)

num_yes_match <- match_tibble |>
  filter(polio_vop1_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- colonia_tibble |>
  count(polio_vop1_should)

num_yes_should <- should_tibble |>
  filter(polio_vop1_should == "YES") |>
  pull(n)
print(num_yes_should)

polio_vop1_percent_adherence = num_yes_match / num_yes_should
print(polio_vop1_percent_adherence)

###### Polio VOP 2 #########

match_tibble <- colonia_tibble |>
  count(polio_vop2_match)

num_yes_match <- match_tibble |>
  filter(polio_vop2_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- colonia_tibble |>
  count(polio_vop2_should)

num_yes_should <- should_tibble |>
  filter(polio_vop2_should == "YES") |>
  pull(n)
print(num_yes_should)

polio_vop2_percent_adherence = num_yes_match / num_yes_should
print(polio_vop2_percent_adherence)
###### Penta 1 #########

match_tibble <- colonia_tibble |>
  count(penta1_match)

num_yes_match <- match_tibble |>
  filter(penta1_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- colonia_tibble |>
  count(penta1_should)

num_yes_should <- should_tibble |>
  filter(penta1_should == "YES") |>
  pull(n)
print(num_yes_should)

penta1_percent_adherence = num_yes_match / num_yes_should
print(penta1_percent_adherence)

###### Penta 2 #########

match_tibble <- colonia_tibble |>
  count(penta2_match)

num_yes_match <- match_tibble |>
  filter(penta2_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- colonia_tibble |>
  count(penta2_should)

num_yes_should <- should_tibble |>
  filter(penta2_should == "YES") |>
  pull(n)
print(num_yes_should)

penta2_percent_adherence = num_yes_match / num_yes_should
print(penta2_percent_adherence)

###### Penta 3 #########

match_tibble <- colonia_tibble |>
  count(penta3_match)

num_yes_match <- match_tibble |>
  filter(penta3_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- colonia_tibble |>
  count(penta3_should)

num_yes_should <- should_tibble |>
  filter(penta3_should == "YES") |>
  pull(n)
print(num_yes_should)

penta3_percent_adherence = num_yes_match / num_yes_should
print(penta3_percent_adherence) ##we should double check this one because why is it at 100%-

###### Neumo 1 #########

match_tibble <- colonia_tibble |>
  count(neumo1_match)

num_yes_match <- match_tibble |>
  filter(neumo1_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- colonia_tibble |>
  count(neumo1_should)

num_yes_should <- should_tibble |>
  filter(neumo1_should == "YES") |>
  pull(n)
print(num_yes_should)

neumo1_percent_adherence = num_yes_match / num_yes_should
print(neumo1_percent_adherence)

###### Neumo 2 #########

match_tibble <- colonia_tibble |>
  count(neumo2_match)

num_yes_match <- match_tibble |>
  filter(neumo2_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- colonia_tibble |>
  count(neumo2_should)

num_yes_should <- should_tibble |>
  filter(neumo2_should == "YES") |>
  pull(n)
print(num_yes_should)

neumo2_percent_adherence = num_yes_match / num_yes_should
print(neumo2_percent_adherence)

###### Neumo 3 #########

match_tibble <- colonia_tibble |>
  count(neumo3_match)

num_yes_match <- match_tibble |>
  filter(neumo3_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- colonia_tibble |>
  count(neumo3_should)

num_yes_should <- should_tibble |>
  filter(neumo3_should == "YES") |>
  pull(n)
print(num_yes_should)

neumo3_percent_adherence = num_yes_match / num_yes_should
print(neumo3_percent_adherence)

###### Rota 1 #########

match_tibble <- colonia_tibble |>
  count(rota1_match)

num_yes_match <- match_tibble |>
  filter(rota1_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- colonia_tibble |>
  count(rota1_should)

num_yes_should <- should_tibble |>
  filter(rota1_should == "YES") |>
  pull(n)
print(num_yes_should)

rota1_percent_adherence = num_yes_match / num_yes_should
print(rota1_percent_adherence)

###### Rota 2 #########

match_tibble <- colonia_tibble |>
  count(rota2_match)

num_yes_match <- match_tibble |>
  filter(rota2_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- colonia_tibble |>
  count(rota2_should)

num_yes_should <- should_tibble |>
  filter(rota2_should == "YES") |>
  pull(n)
print(num_yes_should)

rota2_percent_adherence = num_yes_match / num_yes_should
print(rota2_percent_adherence)

###### SRP 1 #########

match_tibble <- colonia_tibble |>
  count(srp1_match)

num_yes_match <- match_tibble |>
  filter(srp1_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- colonia_tibble |>
  count(srp1_should)

num_yes_should <- should_tibble |>
  filter(srp1_should == "YES") |>
  pull(n)
print(num_yes_should)

srp1_percent_adherence = num_yes_match / num_yes_should
print(srp1_percent_adherence)

###### SRP 2 #########

match_tibble <- colonia_tibble |>
  count(srp2_match)

num_yes_match <- match_tibble |>
  filter(srp2_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- colonia_tibble |>
  count(srp2_should)

num_yes_should <- should_tibble |>
  filter(srp2_should == "YES") |>
  pull(n)
print(num_yes_should)

srp2_percent_adherence = num_yes_match / num_yes_should
print(srp2_percent_adherence)

###### Hep A #########

match_tibble <- colonia_tibble |>
  count(hep_a_match)

num_yes_match <- match_tibble |>
  filter(hep_a_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- colonia_tibble |>
  count(hep_a_should)

num_yes_should <- should_tibble |>
  filter(hep_a_should == "YES") |>
  pull(n)
print(num_yes_should)

hep_a_percent_adherence = num_yes_match / num_yes_should
print(hep_a_percent_adherence)

###### DPT 1 #########

match_tibble <- colonia_tibble |>
  count(dpt1_match)

num_yes_match <- match_tibble |>
  filter(dpt1_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- colonia_tibble |>
  count(dpt1_should)

num_yes_should <- should_tibble |>
  filter(dpt1_should == "YES") |>
  pull(n)
print(num_yes_should)

dpt1_percent_adherence = num_yes_match / num_yes_should
print(dpt1_percent_adherence)

###### DPT 2 #########

match_tibble <- colonia_tibble |>
  count(dpt2_match)

num_yes_match <- match_tibble |>
  filter(dpt2_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- colonia_tibble |>
  count(dpt2_should)

num_yes_should <- should_tibble |>
  filter(dpt2_should == "YES") |>
  pull(n)
print(num_yes_should)

dpt2_percent_adherence = num_yes_match / num_yes_should
print(dpt2_percent_adherence)

###### VPH 1 #########

match_tibble <- colonia_tibble |>
  count(vph_1_match)

num_yes_match <- match_tibble |>
  filter(vph_1_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- colonia_tibble |>
  count(vph_1_should)

num_yes_should <- should_tibble |>
  filter(vph_1_should == "YES") |>
  pull(n)
print(num_yes_should)

vph_1_percent_adherence = num_yes_match / num_yes_should
print(vph_1_percent_adherence)

###### Tetanus Diptheria #########

match_tibble <- colonia_tibble |>
  count(tetanus_dip_match)

num_yes_match <- match_tibble |>
  filter(tetanus_dip_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- colonia_tibble |>
  count(tetanus_dip_should)

num_yes_should <- should_tibble |>
  filter(tetanus_dip_should == "YES") |>
  pull(n)
print(num_yes_should)

tetanus_dip_percent_adherence = num_yes_match / num_yes_should
print(tetanus_dip_percent_adherence)
```

```{r}
#| label: each-vax-adherence-calcs-for-NOT-colonia

not_colonia_tibble <- new_tibble |>
  filter(colonia_status.x == "No")

###### Hep B ######
match_tibble <- not_colonia_tibble |>
  count(hep_b_match)

num_yes_match <- match_tibble |>
  filter(hep_b_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- not_colonia_tibble |>
  count(hep_b_should)

num_yes_should <- should_tibble |>
  filter(hep_b_should == "YES") |>
  pull(n)
print(num_yes_should)

hep_b_percent_adherence = num_yes_match / num_yes_should
print(hep_b_percent_adherence)

######  BCG  #########

match_tibble <- not_colonia_tibble |>
  count(bcg_match)

num_yes_match <- match_tibble |>
  filter(bcg_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- not_colonia_tibble |>
  count(bcg_should)

num_yes_should <- should_tibble |>
  filter(bcg_should == "YES") |>
  pull(n)
print(num_yes_should)

bcg_percent_adherence = num_yes_match / num_yes_should
print(bcg_percent_adherence)

###### Polio VPI 1 #########

match_tibble <- not_colonia_tibble |>
  count(polio_vpi1_match)

num_yes_match <- match_tibble |>
  filter(polio_vpi1_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- not_colonia_tibble |>
  count(polio_vpi1_should)

num_yes_should <- should_tibble |>
  filter(polio_vpi1_should == "YES") |>
  pull(n)
print(num_yes_should)

polio_vpi1_percent_adherence = num_yes_match / num_yes_should
print(polio_vpi1_percent_adherence)

###### Polio VPI 2 #########

match_tibble <- not_colonia_tibble |>
  count(polio_vpi2_match)

num_yes_match <- match_tibble |>
  filter(polio_vpi2_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- not_colonia_tibble |>
  count(polio_vpi2_should)

num_yes_should <- should_tibble |>
  filter(polio_vpi2_should == "YES") |>
  pull(n)
print(num_yes_should)

polio_vpi2_percent_adherence = num_yes_match / num_yes_should
print(polio_vpi2_percent_adherence)

###### Polio VOP 1 #########

match_tibble <- not_colonia_tibble |>
  count(polio_vop1_match)

num_yes_match <- match_tibble |>
  filter(polio_vop1_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- not_colonia_tibble |>
  count(polio_vop1_should)

num_yes_should <- should_tibble |>
  filter(polio_vop1_should == "YES") |>
  pull(n)
print(num_yes_should)

polio_vop1_percent_adherence = num_yes_match / num_yes_should
print(polio_vop1_percent_adherence)

###### Polio VOP 2 #########

match_tibble <- not_colonia_tibble |>
  count(polio_vop2_match)

num_yes_match <- match_tibble |>
  filter(polio_vop2_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- not_colonia_tibble |>
  count(polio_vop2_should)

num_yes_should <- should_tibble |>
  filter(polio_vop2_should == "YES") |>
  pull(n)
print(num_yes_should)

polio_vop2_percent_adherence = num_yes_match / num_yes_should
print(polio_vop2_percent_adherence)
###### Penta 1 #########

match_tibble <- not_colonia_tibble |>
  count(penta1_match)

num_yes_match <- match_tibble |>
  filter(penta1_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- not_colonia_tibble |>
  count(penta1_should)

num_yes_should <- should_tibble |>
  filter(penta1_should == "YES") |>
  pull(n)
print(num_yes_should)

penta1_percent_adherence = num_yes_match / num_yes_should
print(penta1_percent_adherence)

###### Penta 2 #########

match_tibble <- not_colonia_tibble |>
  count(penta2_match)

num_yes_match <- match_tibble |>
  filter(penta2_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- not_colonia_tibble |>
  count(penta2_should)

num_yes_should <- should_tibble |>
  filter(penta2_should == "YES") |>
  pull(n)
print(num_yes_should)

penta2_percent_adherence = num_yes_match / num_yes_should
print(penta2_percent_adherence)

###### Penta 3 #########

match_tibble <- not_colonia_tibble |>
  count(penta3_match)

num_yes_match <- match_tibble |>
  filter(penta3_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- not_colonia_tibble |>
  count(penta3_should)

num_yes_should <- should_tibble |>
  filter(penta3_should == "YES") |>
  pull(n)
print(num_yes_should)

penta3_percent_adherence = num_yes_match / num_yes_should
print(penta3_percent_adherence) ##we should double check this one because why is it at 100%-

###### Neumo 1 #########

match_tibble <- not_colonia_tibble |>
  count(neumo1_match)

num_yes_match <- match_tibble |>
  filter(neumo1_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- not_colonia_tibble |>
  count(neumo1_should)

num_yes_should <- should_tibble |>
  filter(neumo1_should == "YES") |>
  pull(n)
print(num_yes_should)

neumo1_percent_adherence = num_yes_match / num_yes_should
print(neumo1_percent_adherence)

###### Neumo 2 #########

match_tibble <- not_colonia_tibble |>
  count(neumo2_match)

num_yes_match <- match_tibble |>
  filter(neumo2_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- not_colonia_tibble |>
  count(neumo2_should)

num_yes_should <- should_tibble |>
  filter(neumo2_should == "YES") |>
  pull(n)
print(num_yes_should)

neumo2_percent_adherence = num_yes_match / num_yes_should
print(neumo2_percent_adherence)

###### Neumo 3 #########

match_tibble <- not_colonia_tibble |>
  count(neumo3_match)

num_yes_match <- match_tibble |>
  filter(neumo3_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- not_colonia_tibble |>
  count(neumo3_should)

num_yes_should <- should_tibble |>
  filter(neumo3_should == "YES") |>
  pull(n)
print(num_yes_should)

neumo3_percent_adherence = num_yes_match / num_yes_should
print(neumo3_percent_adherence)

###### Rota 1 #########

match_tibble <- not_colonia_tibble |>
  count(rota1_match)

num_yes_match <- match_tibble |>
  filter(rota1_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- not_colonia_tibble |>
  count(rota1_should)

num_yes_should <- should_tibble |>
  filter(rota1_should == "YES") |>
  pull(n)
print(num_yes_should)

rota1_percent_adherence = num_yes_match / num_yes_should
print(rota1_percent_adherence)

###### Rota 2 #########

match_tibble <- not_colonia_tibble |>
  count(rota2_match)

num_yes_match <- match_tibble |>
  filter(rota2_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- not_colonia_tibble |>
  count(rota2_should)

num_yes_should <- should_tibble |>
  filter(rota2_should == "YES") |>
  pull(n)
print(num_yes_should)

rota2_percent_adherence = num_yes_match / num_yes_should
print(rota2_percent_adherence)

###### SRP 1 #########

match_tibble <- not_colonia_tibble |>
  count(srp1_match)

num_yes_match <- match_tibble |>
  filter(srp1_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- not_colonia_tibble |>
  count(srp1_should)

num_yes_should <- should_tibble |>
  filter(srp1_should == "YES") |>
  pull(n)
print(num_yes_should)

srp1_percent_adherence = num_yes_match / num_yes_should
print(srp1_percent_adherence)

###### SRP 2 #########

match_tibble <- not_colonia_tibble |>
  count(srp2_match)

num_yes_match <- match_tibble |>
  filter(srp2_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- not_colonia_tibble |>
  count(srp2_should)

num_yes_should <- should_tibble |>
  filter(srp2_should == "YES") |>
  pull(n)
print(num_yes_should)

srp2_percent_adherence = num_yes_match / num_yes_should
print(srp2_percent_adherence)

###### Hep A #########

match_tibble <- not_colonia_tibble |>
  count(hep_a_match)

num_yes_match <- match_tibble |>
  filter(hep_a_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- not_colonia_tibble |>
  count(hep_a_should)

num_yes_should <- should_tibble |>
  filter(hep_a_should == "YES") |>
  pull(n)
print(num_yes_should)

hep_a_percent_adherence = num_yes_match / num_yes_should
print(hep_a_percent_adherence)

###### DPT 1 #########

match_tibble <- not_colonia_tibble |>
  count(dpt1_match)

num_yes_match <- match_tibble |>
  filter(dpt1_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- not_colonia_tibble |>
  count(dpt1_should)

num_yes_should <- should_tibble |>
  filter(dpt1_should == "YES") |>
  pull(n)
print(num_yes_should)

dpt1_percent_adherence = num_yes_match / num_yes_should
print(dpt1_percent_adherence)

###### DPT 2 #########

match_tibble <- not_colonia_tibble |>
  count(dpt2_match)

num_yes_match <- match_tibble |>
  filter(dpt2_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- not_colonia_tibble |>
  count(dpt2_should)

num_yes_should <- should_tibble |>
  filter(dpt2_should == "YES") |>
  pull(n)
print(num_yes_should)

dpt2_percent_adherence = num_yes_match / num_yes_should
print(dpt2_percent_adherence)

###### VPH 1 #########

match_tibble <- not_colonia_tibble |>
  count(vph_1_match)

num_yes_match <- match_tibble |>
  filter(vph_1_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- not_colonia_tibble |>
  count(vph_1_should)

num_yes_should <- should_tibble |>
  filter(vph_1_should == "YES") |>
  pull(n)
print(num_yes_should)

vph_1_percent_adherence = num_yes_match / num_yes_should
print(vph_1_percent_adherence)

###### Tetanus Diptheria #########

match_tibble <- not_colonia_tibble |>
  count(tetanus_dip_match)

num_yes_match <- match_tibble |>
  filter(tetanus_dip_match == "YES") |>
  pull(n)
print(num_yes_match)

should_tibble <- not_colonia_tibble |>
  count(tetanus_dip_should)

num_yes_should <- should_tibble |>
  filter(tetanus_dip_should == "YES") |>
  pull(n)
print(num_yes_should)

tetanus_dip_percent_adherence = num_yes_match / num_yes_should
print(tetanus_dip_percent_adherence)

```

```{r eval = FALSE}
#| label: for-loop-attempts

#########

should_and_match_cols_only <- new_tibble |>
  select(hep_b_should:tetanus_dip_match) 

for(i in should_and_match_cols_only)
{
  should_and_match_cols_only |>
    select(all_of(i)) 
}

#########

  for (i in seq(from = 27, to = 68, by = 2)) 
  {
    should_tibble <- new_tibble |>
      count(new_tibble[i])
    
    num_yes_should <- should_tibble |>
      filter(new_tibble[i] == "YES") |>
      pull(n)
    
    match_tibble <- new_tibble |>
      count(new_tibble[i+1])

    num_yes_match <- match_tibble |>
      filter(new_tibble[i+1] == "YES") |>
      pull(n)

    percent_adherence = num_yes_match / num_yes_should
    print(percent_adherence)
  }

########

for (i in seq(from = 27, to = 29, by = 2)) 
  {
    should_col <- new_tibble[i]
    match_col <- new_tibble[i+1]
  
    should_col |>
      count() 
    
    match_col |>
      count()
}

########

should_col <- new_tibble[1][27]
match_col <- new_tibble[1][28]
  
    should_col 
    
    match_col 
    
########

should_tibble <- new_tibble |>
      count(should_col)
    
    num_yes_should <- should_tibble |>
      filter(should_col == "YES") |>
      pull(n)
    
    match_tibble <- new_tibble |>
      count(match_col)

    num_yes_match <- match_tibble |>
      filter(match_col == "YES") |>
      pull(n)

    percent_adherence = num_yes_match / num_yes_should
    print(percent_adherence)



```

```{r}
#| label: vax-score-calc

joined_vax_cards <- joined_vax_cards |>
  mutate(vax_score = yes_count / desired_vax_score)

joined_vax_cards |> ggplot(
  aes(x = age_rounded, y = vax_score, color = colonia_status.x)
) +
  geom_point()

joined_vax_cards |>
  group_by(colonia_status.x) |>
  summarise(mean(vax_score))

joined_vax_cards |>
  filter(vax_score > 1)
  
```
